mitodl/edx-api-client

- README.md
I added a badge to report code coverage to ``README.md``.
> Added coverage badge to readme file

- edx_api/client.py
- edx_api/enrollments/__init__.py
- edx_api/enrollments/fixtures/user_enrollments.json
- edx_api/enrollments/models.py
- edx_api/enrollments/models_test.py
- edx_api/integration_test.py
- requirements.txt
Adds a client for the edX enrollments rest API.
The implementation is not complete and limited to 
`GET /api/enrollment/v1/enrollment`
`edx_api/client.py`
You can run the integration test (being sure that everything is configured) or just setup edX to have 
- a user enrolled in a course
- an access token for this user
take a look at the [edX documentation](http://edx.readthedocs.org/projects/edx-platform-api/en/latest/enrollment/overview.html)
> Added Enrollments interface

- .travis.yml
- edx_api/enrollments/models.py
- edx_api/enrollments/models_test.py
- tox.ini
Adds a helper function to filter the enrolled courses based on a list of course IDs
> Added helpers in the enrollments

- edx_api/client.py
- edx_api/course_detail/__init__.py
- edx_api/course_detail/fixtures/course_detail.json
- edx_api/course_detail/models.py
- edx_api/course_detail/models_test.py
- edx_api/course_structure/models_test.py
- edx_api/integration_test.py
fixes #8 
Introduces an client for the course detail api
`edx_api/course_detail/__init__.py`
usual way: query for details for the edx demo course or run the integration tests
> Added Course Detail endpoint handler

- .travis.yml
- README.md
- edx_api/ccx.py
- edx_api/ccx_test.py
- edx_api/client.py
- edx_api/course_structure/__init__.py
- edx_api/fixtures/ccx_create_response.json
- edx_api/integration_test.py
- pylintrc
- requirements.txt
https://github.com/mitodl/teachersportal/issues/457
Adds support for CCX Creation.
ccx.py
Run it. It's majoritively copy-pasted from ccxcon.
We'll use this in TP.
> Support for CCX creation.

- edx_api/enrollments/models.py
- edx_api/enrollments/models_test.py
> Added additional helpers for enrollments

- edx_api/certificates/__init__.py
- edx_api/certificates/fixtures/certificates.json
- edx_api/certificates/models.py
- edx_api/certificates/models_test.py
- edx_api/client.py
- edx_api/course_detail/models_test.py
- edx_api/integration_test.py
Adds a client for the user certificates
`edx_api/certificates/__init__.py`
then
`edx_api/certificates/models.py`
then
`edx_api/client.py`
then
`edx_api/integration_test.py`
you need to have an instance of devstack running the branch mitocw:gdm_certificates_230
then you need to create a certificate for a course for a user.
Or simply make sure that the integration test run
the PR on the edx side is close to be merged, but still there... you know how it works :-)
> Added certificates

- RELEASE.rst
- edx_api/__init__.py
> Release 0.2.0

- requirements.txt
- test_requirements.txt
> Upgraded some requirements

- test_requirements.txt
> Removed pdbpp to not break compatibility with python 3.4

- RELEASE.rst
- edx_api/__init__.py
- edx_api/certificates/__init__.py
- edx_api/integration_test.py
- requirements.txt
- test_requirements.txt
> Release 0.2.1

- edx_api/client.py
- edx_api/grades/__init__.py
- edx_api/grades/fixtures/current_grades.json
- edx_api/grades/models.py
- edx_api/grades/models_test.py
- edx_api/integration_test.py
fixes #24 
introduces support for the edX current grade rest API introduced with PR https://github.com/edx/edx-platform/pull/13285
`edx_api/grades/__init__.py`
run integration tests: note that the ccx integration test will fail (because of a well known bug on edx)
the edx pr is still under review, even if the overall structure should not change
> Current grade support

- README.md
- RELEASE.rst
- edx_api/__init__.py
- edx_api/client.py
- edx_api/enrollments/__init__.py
- edx_api/enrollments/init_test.py
- edx_api/grades/__init__.py
- edx_api/grades/fixtures/current_grades.json
- edx_api/grades/models.py
- edx_api/grades/models_test.py
- edx_api/integration_test.py
- requirements.txt
- test_requirements.txt
> Release 0.3.0

- .travis.yml
- edx_api/enrollments/models.py
- edx_api/integration_test.py
Fixes #34 
Fixes a problem where codecov was unable to find coverage results
Look at the code coverage for this PR
> Fix codecov

- edx_api/client.py
- edx_api/integration_test.py
- edx_api/user_info/__init__.py
- edx_api/user_info/fixtures/user_info.json
- edx_api/user_info/models.py
- edx_api/user_info/models_test.py
https://github.com/mitodl/micromasters/issues/1375
Adds a client for the user info API
Run the integration tests against your local devstack
> Added user_info client

- test_requirements.txt
None. Trying to help test failures on the release PR#36.
> Specify pylint version

- .travis.yml
- RELEASE.rst
- edx_api/__init__.py
- edx_api/certificates/fixtures/certificates.json
- edx_api/certificates/models.py
- edx_api/certificates/models_test.py
- edx_api/client.py
- edx_api/enrollments/models.py
- edx_api/integration_test.py
- edx_api/user_info/__init__.py
- edx_api/user_info/fixtures/user_info.json
- edx_api/user_info/models.py
- edx_api/user_info/models_test.py
- test_requirements.txt
> Release 0.4.0

- requirements.txt
fixe https://github.com/mitodl/micromasters/issues/4150#issuecomment-433386101
it upgrade six. Which is essential for django 2.1.2 upgrade
see everything works fine
@pdpinch
> Update six version to latest

- edx_api/grades/__init__.py
- edx_api/grades/fixtures/current_grades.json
- edx_api/grades/models.py
- edx_api/grades/models_test.py
The deprecation notice [link](https://groups.google.com/d/msgid/edx-code/CACSOLjctD34-RVnEGMYGHpkdsPbSH69YGCkcHqdTF%3DLPHk%3Dg8Q%40mail.gmail.com?utm_medium=email&utm_source=footer)
Update Grades API to v1
https://github.com/edx/edx-platform/blob/master/lms/djangoapps/grades/api/v1/views.py
> Update grades API to v1

- edx_api/client.py
- edx_api/email_settings.py
- edx_api/email_settings_test.py
- tox.ini
https://github.com/mitodl/mitxonline/issues/288
add api client for edx change email settings
> add api client for edx change email settings

- edx_api/enrollments/__init__.py
https://github.com/mitodl/micromasters/issues/5193
- Adds a new function to create `Verified` mode enrollments
- Installing it in the MM, And then enrolling a user with open edX.
- Install the client from this branch
- Enroll a user in `Verified` mode in edX course
- This will require integration of edX with MicroMasters
More details are mentioned in https://github.com/mitodl/micromasters/issues/5193
**NOTE:** 
1 - This PR is based on `Verified` mode and I created this PR just in advance as we still need to finalize the mode to be used as mentioned in [this comment](https://github.com/mitodl/micromasters/issues/5193#issuecomment-1097914534)
2- This PR is currently not tested since I don't have a working local edX/MicroMasters integration.
> feat: add Verified mode enrollment creation

- edx_api/course_detail/__init__.py
https://github.com/mitodl/mitxonline/issues/842
Adds parentheses
> parentheses

- edx_api/bulk_user_retirement.py
- edx_api/client.py
Fixes https://github.com/mitodl/mitxonline/issues/697
Adds the user bulk retirement API client.
Follow the testing steps of this [MITxOnline PR](https://github.com/mitodl/mitxonline/pull/1785#issue-1824315167).
> feat: add bulk retirement api
